### ISSUE TITLE
Edit / delete buttons disapear

### ISSUE THREAD

**Issue by Rogal-exe** [TJPoorman/home_maintenance#81]
### System Health details

Hello,

i have a problem becasue edit / delete -  buttons disapear 

<img width="2489" height="543" alt="Image" src="https://github.com/user-attachments/assets/e02e44c7-ead0-49da-98fd-b30ef55bffad" />

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/TJPoorman/home_maintenance/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

i have a problem becasue edit / delete -  buttons disapear 

### Reproduction steps

i have a problem becasue edit / delete -  buttons disapear 

### Debug logs

```text
i have a problem becasue edit / delete -  buttons disapear
```

**Comment by DavyRoswinkel** [comment]
I Just saw 3 dots in firefix, behind the checkbutton.
Tried to click it, it showed edit and remove but it wasn't clickable.

I tried chrome, the 3 dots aren't visable.
Refreshed firefix but the 3 dots are gone.

**Comment by tkurnik** [comment]
I have this same issue.  Tried 3 different browsers and about 3 different themes.

**Comment by Safislab777** [comment]
same issue here. No way to edit/ delete entries

**Comment by Safislab777** [comment]
Seems like it's been fixed with newest HA 11.2. 
Edit- it was working until I updated a different integration and reloaded the front end.

**Comment by nilsreiter** [comment]
No, still present for me in 2025.11.2

**Comment by Safislab777** [comment]
> No, still present for me in 2025.11.2

That’s strange. It’s fixed for me in Crome and Kiosk browser but not on the companion app.

**Comment by DavyRoswinkel** [comment]
I now have 2025.11.2
But still same issue in chrome, firefox and the companion app.

**Comment by tkurnik** [comment]
Yea, still an issue for me, too, on HA 11.2 with Safari, Firefox, Atlas, companion app...

**Comment by Safislab777** [comment]
@TJPoorman any ideas on this?

**Comment by bricktopm** [comment]
Same issue here, tried in HA app, safari, chrome,

**Comment by Momro** [comment]
Fixed in my PR. Awaiting merge :-)
